language: node_js
node_js:
  - "0.10"

after_script:
  - if [[ `node --version` == *v0.10* ]]; then cat ./coverage/lcov-report/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

notifications:
  slack: mojs:n6WXx45anfQn03fJu5Yw0Btt